import Head from 'next/head'
import styles from '../styles/Home.module.css'
import InputField from '../components/InputField'
import ButtonField from '../components/ButtonField'
import Header from '../components/Header'
import JobCard from '../components/JobCard'
import ApplicantCard from '../components/ApplicantCard'

export default function CompanyDashboard() {
  return (
    <div>
      <Head>
    
        <meta name="description" content="Generated by create next app" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous"/>
        <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
        />
      </Head>
      <Header/>


      <div className='container'>
        <div className='row mt-4 mb-4'>
            <div className='col-lg-8'>
            <h3 className='fw-bold'>Applicants</h3>
            </div>
            <div className='col-lg-4'>
                <ButtonField buttonText="Post New internship" buttonClass="bt-background"/>
            </div>
        </div>
        

        <div className='row mt-4'>
        <ApplicantCard 
            profile="Backend Developer"
            studentName="Ekundayo Isiah"
            skills="React, Next, Photoshop, Html, Nidejs"         
        />
        <ApplicantCard 
            profile="Frontend Developer"
            studentName="Balogun Victor"
            skills="React, Next, Photoshop, Html, Nidejs"        
        />
        <ApplicantCard 
            profile="Graphics Designer"
            studentName="Dozie Francis"
            skills="React, Next, Photoshop, Html, Nidejs"       
        />
        </div>
        

      </div>
      
    </div>
  )
}
