import Head from 'next/head'
import styles from '../styles/Home.module.css'
import InputField from '../components/InputField'
import ButtonField from '../components/ButtonField'
import SearchField from '../components/SearchField'
import Header from '../components/Header'
import JobCard from '../components/JobCard'

export default function StudentProfile() {
  return (
    <div>
      <Head>
    
        <meta name="description" content="Generated by create next app" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous"/>
        <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
        />
      </Head>
      
      <Header/>
      <div className='job-container'>
       
        <h1 className='main-job-heading'>Frontend Developer Intern (React Js) at Blackcopper Services</h1>
        
        <p className='sub-job-heading mt-4 mb-4'>Cover Letter</p>
        <textarea className="form-control mb-4" id="exampleFormControlTextarea1" rows="4" placeholder='write a brief cover letter of why you would be a good fit for this company( now would be a good time to convince them)'></textarea>
        <ButtonField buttonText="Submit" buttonClass="bt-background "/>
    </div>
    </div>
  )
}
