import Head from 'next/head'
import styles from '../styles/Home.module.css'
import InputField from '../components/InputField'
import ButtonField from '../components/ButtonField'
import SearchField from '../components/SearchField'
import Header from '../components/Header'
import JobCard from '../components/JobCard'

export default function StudentProfile() {
  return (
    <div>
      <Head>
  
        <meta name="description" content="Generated by create next app" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous"/>
        <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
        />
      </Head>
      
      <Header/>
      <div className='job-container'>
       
        <h1 className='main-job-heading'>Frontend Developer</h1>
        <p className='color'>Balogun Victor</p>

        <div className='mt-2'>
            <b>Bio</b>
            <p>You can add webfonts, meta tags, or analytics to this file.
            The build step will</p>
        </div>
        
        <div className='row mt-3 mb-4'>
        <div className='col-md'>
            <b className='text-secondary'>Gender</b>
            <p>Male</p>
        </div>
        <div className='col-md'>
            <b className='text-secondary'>Status</b>
            <p>Under Graduate</p>
        </div>
        <div className='col-md'>
            <b className='text-secondary'>Location</b>
            <p>Lagos</p>
        </div>

    </div>
    <p className='borderr text-secondary'>Intern</p>
    <hr className='mt-3'/>
    <p className='sub-job-heading mt-2'>Cover Letter</p>
    <p className='job-text'>You can add webfonts, meta tags, or analytics to this file.
      The build step will place the bundled scripts into the  tag.
      To begin the development, run `npm start` or `yarn start`.
      To create a production bundle, use `npm run build` or `yarn build`.</p>
      <p className='sub-job-heading mt-2'>Availability</p>
    <p className='job-text'>You can add webfonts, meta tags, or analytics to this file.
      The build step will place the bundled scripts into the  tag.
    </p>
    <hr className='mt-3'/>
    <div className='row mt-3 mb-4'>
        <div className='col-md'>
            <b className='text-secondary'>Course Of Study</b>
            <p>Computer Science</p>
        </div>
        <div className='col-md'>
            <b className='text-secondary'>School</b>
            <p>Covenant University</p>
        </div>
        <div className='col-md'>
            <b className='text-secondary'>Class</b>
            <p>First Class</p>
        </div>
    </div>
    
    <p className='sub-job-heading mt-2'>Experience</p>
    <div className='row mt-3 mb-4'>
        <div className='col-md'>
            <b className='text-secondary'>Job Title</b>
            <p>IT support Intern</p>
        </div>
        <div className='col-md'>
            <b className='text-secondary'>Company</b>
            <p>Blackcopper Limited</p>
        </div>
    </div>
    <p className='sub-job-heading mt-2'>Certifications</p>
    <div className='row mt-3 mb-4'>
        <div className='col-md'>
            <b className='text-secondary'>Certificate Title</b>
            <p>Computer Science </p>
        </div>
        <div className='col-md'>
            <b className='text-secondary'>Certificate Org</b>
            <p>Coursera</p>
        </div>
    </div>
    <p className='sub-job-heading mt-2'>Skills</p>
    <ul>
        <li className='resp'>
        HTML
        </li>
        <li className='resp'>
        javascript
        </li>
        <li className='resp'>
        react
        </li>
        <li className='resp'>
        node
        </li>
        
    </ul>
    <p className='sub-job-heading mt-2'>Projects</p>
    <p className='job-text'>balogun.com</p>
    <hr className='mt-3'/>
    
    
    <div className='row mt-3 mb-4'>
        <div className='col-md'>
            <ButtonField buttonText="Accept" buttonClass="bt-background "/>
        </div>
        <div className='col-md'>
            <ButtonField buttonText="Decline" buttonClass="bt-background "/>
        </div>
        
    </div>

       
    </div>
    </div>
  )
}
