import Head from 'next/head'
import styles from '../styles/Home.module.css'
import InputField from '../components/InputField'
import ButtonField from '../components/ButtonField'
import Header from '../components/Header'
import { useState } from 'react'
import axios from 'axios'
import {setcurrentStudentSession} from './Utils/common'
import { useCookies } from 'react-cookie';
import { useEffect } from 'react';
import { useRouter} from 'next/router'

export default function StudentProfile() {
  const [orgDescription, setorgDescription] = useState('');
  const [website, setwebsite] = useState('');
  const [socialHandles, setsocialHandles] = useState('');
  
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  const [cookies, setCookie] = useCookies();
  const router = useRouter()


  const isauth = () => {
    if(!cookies.authToken){
      router.push('/login')
    }
    else{
      console.log("you are welcome")
    }
  }
    

  useEffect(() => {
    isauth();
  }, [])


  const submit = async (e) => {
    e.preventDefault();
    
    setError(null);
    setLoading(true)
    
    axios.post("http://localhost:4070/api/company/profile/update", {
        orgDescription: orgDescription,
        orgPresence: {website:website, socialHandles:{socialHandles}, },
    } , { withCredentials: true, 
    }).then(response => {
        setLoading(false)
        router.push("/companyDashboard");
        // setcurrentStudentSession(response.data.authToken, response.data.currentCompany)
        console.log('response', response)
    }).catch(error => {
        setLoading(false);
        if(error.code === "ERR_BAD_REQUEST"){
            setError(error.response.data.error)
        }
        
        else{
            setError("something went wrong, Please Try again later")
        }
        console.error('error >>> ', error);
    });
}

  
  return (
    <div>
      <Head>
    
        <meta name="description" content="Generated by create next app" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous"/>
        <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
        />
      </Head>
      <Header/>
      <div className='profile-container'>
        <center>
        <h1 className='mb-4'>Complete Your Profile</h1>
        </center>
        <form onSubmit={submit}>
        <div className='row'>
          <div className='company-profile'>
          <textarea className="form-control mb-4" id="exampleFormControlTextarea1" rows="3" placeholder='Description Of Your Organisation' onChange={e => setorgDescription(e.target.value)}>{orgDescription}</textarea>
          <input className='custom-input' placeholder="organization website" type="text" value={website} onChange={e => setwebsite(e.target.value)} />
            
           <b>Company Online Presence</b> 
           <input className='custom-input' placeholder="Social Link(facebook, instagram, etc)" type="text" value={socialHandles} onChange={e => setsocialHandles(e.target.value)} />
           
          </div>
          
        </div>
        <div className='container-btn'>
        {error && <div className='mt-2 text-danger'>{error}</div>}
        <ButtonField buttonText="Submit" buttonClass="bt-background width"/>
        </div>
        
        </form>
        
      </div>
      
    </div>
  )
}
