import Head from 'next/head'
import styles from '../styles/Home.module.css'
import InputField from '../components/InputField'
import ButtonField from '../components/ButtonField'
import Header from '../components/Header'
import JobCard from '../components/JobCard'
import PostingCard from '../components/PostingCard'
import Router from "next/router";
import Link from 'next/link'
import {  removecurrentStudentSession, setcurrentStudentSession, getcurrentcompany } from '../pages/Utils/common2'
import { useEffect, useState } from "react";

export default function CompanyDashboard() {

  const currentCompany = getcurrentcompany()



  return (
    <div>
      <Head>
    
        <meta name="description" content="Generated by create next app" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous"/>
        <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
        />
      </Head>
      <Header/>


      <div className='container'>
        <div className='row mt-4 mb-4'>
            <div className='col-lg-8'>
            <h6 className='fw-bold'>welcome  {currentCompany.adminFirstName}</h6>
            <h3 className='text-secondary'>Internships</h3>
           
            </div>
            <div className='col-lg-4'>
              <Link href="/postInternship">
              <ButtonField buttonText="Post New internship" buttonClass="bt-background"/>
              </Link>
               
            </div>
        </div>
        

        <div className='row mt-4'>
        <PostingCard 
            jobTitle="Frontend Developer(React)"
            status="Under Processing"
            applicants="0"
            actions="0"           
        />
        <PostingCard 
            jobTitle="Frontend Developer(React)"
            status="Under Processing"
            applicants="0"
            actions="0"           
        />
        <PostingCard 
            jobTitle="Frontend Developer(React)"
            status="Under Processing"
            applicants="0"
            actions="0"           
        />
        </div>
        

      </div>
      
    </div>
  )
}
