import Head from 'next/head'
import styles from '../styles/Home.module.css'
import InputField from '../components/InputField'
import ButtonField from '../components/ButtonField'
import Header from '../components/Header'

export default function StudentProfile() {
  return (
    <div>
      <Head>
    
        <meta name="description" content="Generated by create next app" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous"/>
        <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
        />
      </Head>
      <Header/>
      <div className='profile-container'>
        <center>
        <h1 className='mb-4'>Complete Your Profile</h1>
        </center>
        <form>
        <div className='row'>
          <div className='company-profile'>
          <textarea className="form-control mb-4" id="exampleFormControlTextarea1" rows="3" placeholder='Description Of Your Organisation'></textarea>
          <InputField type="text" placeholder="company website(optional)"/>
            

           <b>Company Online Presence</b> 
           <InputField type="text" placeholder="social media link(eg facebook, instagram, linked in)"/>
           <InputField type="text" placeholder="social Profile 2(optional)"/>

            
            
          </div>
          
        </div>
        <div className='container-btn'>
        <ButtonField buttonText="Submit" buttonClass="bt-background width"/>
        </div>
        
        </form>
        
      </div>
      
    </div>
  )
}
