import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
// import styles from '../styles/Home.module.css'
import Header from "../components/Header";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import Internships from "../components/Internships";
import WhatsGreat from "../components/WhatsGreat";
import Cr from "../components/Cr";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <script src="https://cdn.tailwindcss.com"></script>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Cr />
      <WhatsGreat />
      <Internships />
      <Footer />
    </div>
  );
}
