import Head from 'next/head'
import styles from '../styles/Home.module.css'
import InputField from '../components/InputField'
import ButtonField from '../components/ButtonField'
import Header from '../components/Header'

export default function StudentProfile() {
  return (
    <div>
      <Head>
    
        <meta name="description" content="Generated by create next app" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous"/>
        <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
        />
      </Head>
      <Header/>
      <div className='profile-container'>
        <h1 className='mb-4'>Post An Internship</h1>
        <form>
        <div className='row'>
          <div className='col-md profile-box'>
          <InputField type="text" placeholder="Profile"/>
          <InputField type="text" placeholder="Job Title"/>
            <div className='row'>
                <div className='col-md'>
                <InputField type="text" placeholder="Job Type"/>
                </div>
                <div className='col-md'>
                <InputField type="text" placeholder="Salary"/> 
                </div>
            </div>

            <InputField type="text" placeholder="Duration"/>
            <InputField type="text" placeholder="Number Of Openings"/>
            <InputField type="text" placeholder="Location"/>
          </div>
          <div className='col-md profile-box'>
          <h5 className='mb-3 fw-bold text-center'>Interns Responsibilities</h5>
          <textarea className="form-control mb-4" id="exampleFormControlTextarea1" rows="15" placeholder='
            1. Day To day tasks performed By The Intern
            2. Enter duties....
          '></textarea>
          </div>
          <div className='col-md profile-box'>
          <textarea className="form-control mb-4" id="exampleFormControlTextarea1" rows="4" placeholder='
           Enter Skills Required
          '></textarea>
          <textarea className="form-control mb-4" id="exampleFormControlTextarea1" rows="7" placeholder='
           Additional Information(optional)
          '></textarea>
            
            

          </div>
        </div>
        <div className='container-btn'>
        <ButtonField buttonText="Submit" buttonClass="bt-background width"/>
        </div>
        
        </form>
        
      </div>
      
    </div>
  )
}
