import Head from 'next/head'
import styles from '../styles/Home.module.css'
import InputField from '../components/InputField'
import ButtonField from '../components/ButtonField'
import Link from 'next/link'
import Header from '../components/Header'

export default function Register() {
  return (
    <div>
      <Head>
    
        <meta name="description" content="Generated by create next app" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous"/>
        <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
        />
      </Head>
      <Header/>
      
      <div className='register-container '>
        <div className='row'>
            <div className='col-lg pl-4 reg-bg'>
                <h1 className='main-register-header'>Let Us Help You Get Started With Your Dream Career</h1>
                <ul className='register-list'>
                    <li>Internships</li>
                    <li>Partime Gigs</li>
                    <li>Remote Internships</li>
                    <li>NYSC</li>
                    <li>Benefits</li>
                    <li>& More....</li>
                </ul>
            </div>
            <div className='col-lg'>
                <form className='register-form'>
                    <h5 className='text-center mb-3 fw-bold'>Create An Account</h5>

                    <ButtonField buttonText="Register With Google" buttonClass="bt-outline"/>
                    <p className='text-center pt-2'>Or</p>
                    <div className='row'>
                        <div className='col-md'>
                        <InputField type="text" placeholder="First Name"/>
                        </div>
                        <div className='col-md'>
                        <InputField type="text" placeholder="Last Name"/> 
                        </div>
                    </div>

                    <InputField type="email" placeholder="Email Address"/>
                    <InputField type="number" placeholder="Phone Number"/>
                    <InputField type="password" placeholder="Password"/> 

                    
                    <ButtonField buttonText="Register" buttonClass="bt-background"/>
                    
                    <Link href="/login">
                    <p className='color mt-3 mb-2'>Already Have An Account ?</p>
                    </Link>
                      
                </form>
            </div>
        </div>
       
      </div>
      
    </div>
  )
}
