import Head from 'next/head'
import ButtonField from '../components/ButtonField'
import Link from 'next/link'
import Header from '../components/Header'
import { useState } from 'react'

import axios from 'axios'
import { setcurrentStudentSession, getauthToken } from './Utils/common'
import Router from "next/router";
// import { useRouter } from 'next/router'

export default function Register() {
    const [firstname, setfirstname] = useState('');
    const [lastname, setlastname] = useState('');
    const [phoneNumber, setphoneNumber] = useState('');
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [error, setError] = useState("");
    const [loading, setLoading] = useState(false);
    
    const submit = async (e) => {
        e.preventDefault();
        
        setError(null);
        setLoading(true)
        axios.post("http://localhost:4070/api/student/signUp", {
            email: email,
            password: password,
            firstname: firstname,
            lastname: lastname,
            phoneNumber: phoneNumber

        }, {withCredentials:true}).then(response => {
            setLoading(false)
            setcurrentStudentSession(response.data.authToken, response.data.currentStudent)
            Router.push("/login");
            console.log('response', response)
        }).catch(error => {
            setLoading(false);
            if(error.code === "ERR_BAD_REQUEST"){
                setError(error.response.data.error)
            }
            
            else{
                setError("something went wrong, Please Try again later")
            }
            console.error('error >>> ', error);
        });
    }
  return (
    <div>
      <Head>
    
        <meta name="description" content="Generated by create next app" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous"/>
        <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
        />
      </Head>
      <Header/>
      
      <div className='register-container '>
        <div className='row'>
            <div className='col-lg pl-4 reg-bg'>
                <h1 className='main-register-header'>Let Us Help You Get Started With Your Dream Career</h1>
                <ul className='register-list'>
                    <li>Internships</li>
                    <li>Partime Gigs</li>
                    <li>Remote Internships</li>
                    <li>NYSC</li>
                    <li>Benefits</li>
                    <li>& More....</li>
                </ul>
            </div>
            <div className='col-lg'>
                <form onSubmit={submit} className='register-form'>
                    <h5 className='text-center mb-3 fw-bold'>Create An Account</h5>

                    <ButtonField buttonText="Register With Google" buttonClass="bt-outline"/>
                    <p className='text-center pt-2'>Or</p>
                    <div className='row'>
                        <div className='col-md'>
                        <input className='custom-input' placeholder="First Name" type="text" value={firstname} onChange={e => setfirstname(e.target.value)} />
                        </div>
                        <div className='col-md'>
                        <input className='custom-input' placeholder="Lastt Name" type="text" value={lastname} onChange={e => setlastname(e.target.value)} />
                        </div>
                    </div>

                    <input className='custom-input' placeholder="Email" type="text" value={email} onChange={e => setEmail(e.target.value)} />
                    <input className='custom-input' placeholder="Phone Number" type="number" value={phoneNumber} onChange={e => setphoneNumber(e.target.value)} />
                    <input className='custom-input' placeholder="Password" type="password" value={password} onChange={e => setPassword(e.target.value)} />
                    {error && <div className='mt-2 text-danger'>{error}</div>}

                    <ButtonField buttonText={loading ? "Loading...": "Register"} buttonClass="bt-background"/>
                    
                    <Link href="/login">
                    <p className='color mt-3 mb-2'>Already Have An Account ?</p>
                    </Link>
                      
                </form>
            </div>
        </div>
       
      </div>
      
    </div>
  )
}



