import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ButtonField from './ButtonField'
import Link from 'next/link'

export default function Header() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"></link>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

  <nav className="navbar navbar-expand-lg">
  <div className="container-fluid pt-2 pb-2">
    <Link href="/">
    <a className="fw-bold navbar-brand mr-4 pr-4" href="#">
    <Image src="/logobb.png" alt="Vercel Logo" width={145} height={25} />
    </a>
    </Link>
    
    <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span className="fa fa-bars color"></span>
    </button>
    <div className="collapse navbar-collapse" id="navbarSupportedContent">
      <ul className="navbar-nav me-auto mb-2 mb-lg-0">
        <li className="nav-item ml-4 pl-4 leftt">
          <a className="nav-link active" aria-current="page" href="#">Internships</a>
        </li>
        <li className="nav-item">
          <a className="nav-link" href="#">Companies</a>
        </li>
        <li className="nav-item dropdown">
          <a className="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            locations
          </a>
          <ul className="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a className="dropdown-item" href="#">Action</a></li>
            <li><a className="dropdown-item" href="#">Another action</a></li>
            <li><hr className="dropdown-divider"/></li>
            <li><a className="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li className="nav-item">
          <a className="nav-link" href="#">Blog</a>
        </li>
        <li className="nav-item">
          <a className="nav-link" href="#">Info</a>
        </li>
       
      </ul>

      {/* <i class="fa fa-bookmark color mr-4"></i> {" "} */}
      
      <div className='dropdown'>
        <button className="get-started-btn btn " type="submit">Get Started {" "} <i class="fa fa-solid fa-caret-down"></i></button>
        <div className="dropdown-content">
        <Link href="/register">
          <p className='mt-2 mb-3 text-secondary sign-link'>As A Student</p>
        </Link>
         <hr/>
         <Link href="/companyregister">
          <p className='mt-2 mb-3 text-secondary sign-link'>As An Employer</p>
        </Link>
        </div>
      </div>
        

        
          
        
     
    </div>
  </div>
</nav>
      
      


  
      
    </div>
  )
}
