import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import InputField from './InputField'
import ButtonField from './ButtonField'

export default function SearchField(props) {
  return (
    <div>
    <Head>
    
    <meta name="description" content="Generated by create next app" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous"/>
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
    />
  </Head>
    <div className='search-container mb-3'>
      <div className='row'>
        <div className='col-md'>
          <InputField type="text" placeholder="Job Title(eg. app developer)"/>
        </div>
        <div className='col-md'>
          <InputField type="text" placeholder="Location(eg. abuja)"/>
        </div>
      </div>
      <ButtonField buttonText="Search" buttonClass="bt-background"/> 
    </div>
    <hr/>
    </div>
    
  )
}
